(ert-deftest evm-test/find ()
  (with-sandbox
   (let ((emacs-test-path (f-expand "emacs-test")))
     (f-mkdir emacs-test-path)
     (let ((default-directory emacs-test-path))
       (f-mkdir "foo" "bar")
       (f-mkdir "baz")
       (f-touch (f-join "foo" "FOO"))
       (f-touch (f-join "foo" "bar" "BAR"))
       (f-touch (f-join "baz" "BAZ"))
       (should (equal (f-join default-directory "foo" "FOO") (evm-find "FOO")))
       (should (equal (f-join default-directory "foo" "bar" "BAR") (evm-find "BAR")))
       (should (equal (f-join default-directory "baz" "BAZ") (evm-find "BAZ")))
       (should-not (evm-find "qux"))))))
